import Link from "next/link";
import Image from "next/image";
import { readPublicWebsite } from "@/features/public-site/data.server";
import { ServiceCard } from "@/components/public-site/site";

export default async function ServicesPage({ searchParams }: { searchParams: Promise<{ category?: string }> }) {
  const [site, { category }] = await Promise.all([readPublicWebsite(), searchParams]);
  const selected = site.categories.find(item => item.slug === category);
  const services = selected ? site.services.filter(service => service.category_id === selected.id) : site.services;
  return <main><section className="bg-ink text-white"><div className="mx-auto grid max-w-7xl items-center gap-8 px-5 py-14 sm:py-20 md:grid-cols-[1fr_.75fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-on-dark-accent">Our services</p><h1 className="display-type mt-4 text-5xl sm:text-6xl">Find what feels right.</h1><p className="mt-5 max-w-xl text-base leading-8 text-white/75">Explore services at {site.business?.name ?? "our studio"}. Every option shows its duration and price before you book.</p></div><div className="relative hidden aspect-[3/2] overflow-hidden rounded-[1.2rem] md:block"><Image src="/images/service-shave.webp" alt="Grooming tools prepared for a barber service" fill priority sizes="40vw" className="object-cover"/></div></div></section><section className="mx-auto max-w-7xl px-5 py-12 sm:py-16"><nav aria-label="Service categories" className="mb-9 flex flex-wrap gap-2"><Link href="/services" aria-current={!selected ? "page" : undefined} className={`inline-flex min-h-11 items-center rounded-xl px-4 text-sm font-semibold ${!selected ? "bg-accent text-white" : "border border-line bg-surface text-ink hover:bg-accent-soft"}`}>All services</Link>{site.categories.map(item => <Link key={item.id} href={`/services?category=${encodeURIComponent(item.slug)}`} aria-current={selected?.id === item.id ? "page" : undefined} className={`inline-flex min-h-11 items-center rounded-xl px-4 text-sm font-semibold ${selected?.id === item.id ? "bg-accent text-white" : "border border-line bg-surface text-ink hover:bg-accent-soft"}`}>{item.name}</Link>)}</nav><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map((service,index) => <ServiceCard key={service.id} priority={index===0} service={service} currency={site.business?.currency ?? "USD"} category={site.categories.find(item => item.id === service.category_id)?.name}/>)}</div>{!services.length && <div className="surface-card p-8 text-center"><h2 className="text-lg font-semibold">No services here yet</h2><p className="mt-2 text-sm text-muted">Try another category or contact the business for help.</p><Link href="/services" className="button-secondary mt-5">View all services</Link></div>}</section></main>;
}
