import Link from "next/link";
import type { CustomerAppointmentView } from "@/features/appointments/customer-data.server";
import { appointmentStatus } from "@/features/appointments/customer-status";
import { formatBusinessTime } from "@/lib/time";
import { money } from "@/features/public-site/model";
import { StatusBadge } from "@/components/ui/status-badge";
const upcomingStates=new Set(["PENDING","ACCEPTED","AWAITING_PAYMENT","CONFIRMED","CHECKED_IN","IN_PROGRESS"]);
export function AppointmentList({appointments,timezone,limit,direction="asc",emptyTitle="No appointments yet",emptyDescription="When you book a visit, you’ll see its status and details here.",showBookAction=true}:{appointments:CustomerAppointmentView[];timezone:string;limit?:number;direction?:"asc"|"desc";emptyTitle?:string;emptyDescription?:string;showBookAction?:boolean}){const rows=[...appointments].sort((a,b)=>a.starts_at.localeCompare(b.starts_at)*(direction==="asc"?1:-1)),shown=limit?rows.slice(0,limit):rows;return <div className="space-y-3">{shown.map(a=><article key={a.id} className="surface-card p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">{formatBusinessTime(a.starts_at,timezone)}</p><h2 className="display-type mt-2 text-2xl">{a.service_name}</h2><p className="mt-2 text-sm text-muted">{a.staff_name} · {a.duration_minutes} minutes</p></div><StatusBadge value={a.state}>{appointmentStatus(a.state)}</StatusBadge></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-line pt-4 text-sm"><span>{money(a.total_amount,a.currency)}{a.state==="PAYMENT_EXPIRED"?" · payment window expired; time released":a.payment_mode_snapshot!=="PAY_AT_BUSINESS"?` · payment ${a.payment_status==="SUCCEEDED"?"paid":a.payment_status?.toLowerCase()??"not started"}`:" · pay at the business"}</span><Link className="font-semibold text-accent-dark underline underline-offset-4" href={`/account/appointments/${a.id}`}>View details</Link></div></article>)}{!shown.length&&<div className="surface-card p-7 text-center"><h2 className="text-lg font-semibold">{emptyTitle}</h2><p className="mt-2 text-sm leading-6 text-muted">{emptyDescription}</p>{showBookAction&&<Link href="/book" className="button-primary mt-5">Book an appointment</Link>}</div>}</div>}
export function isUpcomingAppointment(a:CustomerAppointmentView){return upcomingStates.has(a.state)}
