"use client";
import {useState} from "react";
import {buttonClass,inputClass,Card,Empty,Table,Time} from "@/features/admin/ui";
import type {AvailabilityResult} from "./schemas";
export function AvailabilityInspector({services,staff,initialDate}:{services:{id:string;name:string;active:boolean}[];staff:{id:string;display_name:string;active:boolean}[];initialDate:string}){
 const [result,setResult]=useState<AvailabilityResult|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function inspect(form:FormData){setBusy(true);setError("");setResult(null);try{const params=new URLSearchParams(Object.entries(Object.fromEntries(form)).map(([k,v])=>[k,String(v)]));const response=await fetch(`/api/availability?${params}`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw Error(body.error??"Could not inspect availability.");setResult(body as AvailabilityResult);}catch(e){setError(e instanceof Error?e.message:"Could not inspect availability.");}finally{setBusy(false);}}
 return <div className="space-y-6"><Card title="Inspect a date"><form action={inspect} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm">Service<select required name="service" className={inputClass} defaultValue="">{services.map(s=><option key={s.id} value={s.id}>{s.name}{s.active?"":" (inactive)"}</option>)}</select></label><label className="text-sm">Staff<select name="staff" className={inputClass} defaultValue=""><option value="">Any available staff</option>{staff.map(s=><option key={s.id} value={s.id}>{s.display_name}{s.active?"":" (inactive)"}</option>)}</select></label><label className="text-sm">Business date<input required name="date" type="date" defaultValue={initialDate} className={inputClass}/></label><button className={`${buttonClass} self-end`} disabled={busy||!services.length}>{busy?"Calculating…":"Calculate availability"}</button><label className="flex items-center gap-2 text-sm sm:col-span-2"><input name="diagnostics" value="true" type="checkbox" defaultChecked/>Include admin diagnostics</label></form><p className="mt-3 text-xs text-muted">The public endpoint returns available times and eligible public staff only. Diagnostics require owner/admin MFA.</p>{error&&<p role="alert" className="mt-4 rounded-lg bg-danger-soft p-3 text-sm text-danger">{error}</p>}</Card>{result&&<><Card title={`${result.service?.name??"Unavailable service"} · ${result.date} · ${result.timezone}`}>{result.service&&<p className="mb-4 text-sm text-muted">{result.service.duration_minutes} min service · {result.scheduling_interval_minutes} min start interval · buffers {result.service.buffer_before_minutes}m before / {result.service.buffer_after_minutes}m after</p>}{result.slots.length?<Table headers={["Start","Eligible staff","Deterministic any-staff choice"]}>{result.slots.map(s=><tr key={s.starts_at}><td><Time value={s.starts_at} zone={result.timezone}/><p className="text-xs text-muted">{s.local_time}</p></td><td>{s.staff.map(v=>v.display_name).join(", ")}</td><td>{s.staff.find(v=>v.id===s.assigned_staff_id)?.display_name??"—"}</td></tr>)}</Table>:<Empty>No times are available for this selection.</Empty>}</Card>{result.diagnostics&&<div className="grid gap-6 lg:grid-cols-2"><Card title="Business hours"><Diagnostics rows={result.diagnostics.business_hours.map(x=>`${x.opens_at}–${x.closes_at}`)}/></Card><Card title="Staff working hours"><Diagnostics rows={result.diagnostics.staff_hours.map(x=>`${x.display_name} · ${x.starts_at}–${x.ends_at}`)}/></Card><Card title="Closures"><Diagnostics rows={result.diagnostics.closures.map(x=>`${x.starts_at}–${x.ends_at} · ${x.reason}`)}/></Card><Card title="Staff exceptions"><Diagnostics rows={result.diagnostics.exceptions.map(x=>`${x.kind} · ${x.starts_at}–${x.ends_at} · ${x.reason}`)}/></Card><Card title="Blocking appointment intervals"><Diagnostics rows={result.diagnostics.blocked_intervals.map(x=>`${x.state} · ${x.starts_at}–${x.ends_at}`)}/></Card></div>}</>}</div>;
}
function Diagnostics({rows}:{rows:string[]}){return rows.length?<ul className="space-y-2 text-sm">{rows.map((r,i)=><li key={i} className="break-words">{r}</li>)}</ul>:<Empty>None for this date.</Empty>;}


