import Link from "next/link";
import Image from "next/image";
import { readPublicWebsite, imageUrl } from "@/features/public-site/data.server";
import { ServiceCard, StaffCard } from "@/components/public-site/site";

export default async function Home() {
  const site = await readPublicWebsite();
  const business = site.business;
  if (!business) return <main className="mx-auto max-w-3xl px-5 py-24 text-center"><p className="eyebrow">Welcome</p><h1 className="display-type mt-4 text-5xl">Our website is getting ready.</h1></main>;
  const customHero = imageUrl(site.website?.hero_image_path);
  const heroImage = customHero ?? "/images/hero-barber.webp";
  const featuredServices = site.services.slice(0, 3);
  const featuredStaff = site.staff.slice(0, 3);
  return <main>
    <section className="relative isolate min-h-[620px] overflow-hidden bg-ink text-white"><Image src={heroImage} alt={customHero ? `${business.name} studio` : "Barber at work in a contemporary studio"} fill priority sizes="100vw" unoptimized={Boolean(customHero)} className="-z-20 object-cover object-[63%_center]"/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-[#211b22]/95 via-[#211b22]/75 to-[#211b22]/10"/><div className="mx-auto flex min-h-[620px] max-w-7xl items-center px-5 py-20 sm:py-24"><div className="max-w-[640px]"><p className="text-xs font-bold uppercase tracking-[.2em] text-on-dark-accent">Welcome to {business.name}</p><h1 className="display-type mt-6 text-[clamp(3.5rem,7vw,6.8rem)] leading-[1.02]">Make your next visit count.</h1><p className="mt-7 max-w-lg text-base leading-8 text-white/85 sm:text-lg">{business.description || `Considered service and an easy way to book at ${business.name}.`}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/book" className="inline-flex min-h-13 items-center justify-center rounded-xl bg-accent-soft px-7 py-3 font-bold text-accent-dark transition hover:bg-white">Book an appointment <span aria-hidden="true" className="ml-3">↗</span></Link><Link href="/services" className="inline-flex min-h-13 items-center justify-center rounded-xl border border-white/50 px-7 py-3 font-semibold text-white transition hover:bg-white/10">Explore services</Link></div><p className="mt-6 text-sm text-white/75">{business.booking_approval_mode === "AUTO_CONFIRM" ? "Choose an available time and reserve your place." : "Choose a time and we’ll confirm your request."}</p></div></div></section>
    {site.announcements[0] && <aside className="border-b border-line bg-accent-soft px-5 py-4 text-center text-sm text-ink"><strong>{site.announcements[0].title}</strong> — {site.announcements[0].body}</aside>}
    <section className="mx-auto max-w-7xl px-5 py-16 sm:py-24"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">The essentials</p><h2 className="display-type mt-3 text-4xl sm:text-5xl">Services worth making time for.</h2></div><Link href="/services" className="text-sm font-semibold text-accent-dark underline underline-offset-4">See every service</Link></div>{featuredServices.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{featuredServices.map(service => <ServiceCard key={service.id} service={service} currency={business.currency} category={site.categories.find(category => category.id === service.category_id)?.name}/>)}</div> : <div className="surface-card p-8 text-center text-muted">Services will be listed here soon. <Link href="/contact" className="font-semibold text-accent-dark underline">Contact us</Link> for details.</div>}</section>
    <section className="bg-sand px-5 py-16 sm:py-24"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-2 lg:gap-16"><div className="relative aspect-[5/4] overflow-hidden rounded-[1.25rem]"><Image src="/images/studio-interior.webp" alt="Contemporary barber studio with welcoming seating" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover"/></div><div><p className="eyebrow">A place to pause</p><h2 className="display-type mt-3 text-4xl sm:text-5xl">Good service starts with the details.</h2><p className="mt-6 max-w-xl text-base leading-8 text-muted">{business.description || `At ${business.name}, every visit is an opportunity to feel looked after.`}</p><div className="mt-8 grid gap-4 border-t border-line pt-6 sm:grid-cols-2"><div><p className="font-semibold text-ink">Clear choices</p><p className="mt-1 text-sm leading-6 text-muted">See service duration and price before you request a time.</p></div><div><p className="font-semibold text-ink">Simple scheduling</p><p className="mt-1 text-sm leading-6 text-muted">Choose a professional and an available slot that fits your day.</p></div></div><Link href="/about" className="mt-8 inline-block text-sm font-semibold text-accent-dark underline underline-offset-4">Get to know us</Link></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:py-24"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">The people</p><h2 className="display-type mt-3 text-4xl sm:text-5xl">Meet your professionals.</h2></div><Link href="/team" className="text-sm font-semibold text-accent-dark underline underline-offset-4">Meet the whole team</Link></div>{featuredStaff.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{featuredStaff.map(staff => <StaffCard key={staff.id} staff={staff} services={site.services.filter(service => site.assignments.some(assignment => assignment.staff_id === staff.id && assignment.service_id === service.id)).map(service => service.name)}/>)}</div> : <p className="text-muted">Team profiles are coming soon.</p>}</section>
    <section className="bg-ink px-5 py-16 text-white sm:py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-on-dark-accent">Easy from start to finish</p><h2 className="display-type mt-3 text-4xl sm:text-5xl">A better way to book.</h2><div className="mt-10 grid gap-6 md:grid-cols-3">{[["01","Choose your service","Explore the work, timing, and price."],["02","Find your time","Select a professional, date, and available slot."],["03","Stay in the know",business.booking_approval_mode === "AUTO_CONFIRM" ? "See your confirmation and any payment next step." : "We’ll review the request and update your booking status."]].map(([number,title,body])=><div key={number} className="border-t border-white/25 pt-5"><span className="text-sm font-bold text-on-dark-accent">{number}</span><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-2 max-w-xs text-sm leading-7 text-white/70">{body}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:py-24"><div className="mb-8"><p className="eyebrow">Inside the studio</p><h2 className="display-type mt-3 text-4xl sm:text-5xl">A feel for the place.</h2></div><div className="grid gap-4 sm:grid-cols-3"><div className="relative aspect-[4/5] overflow-hidden rounded-[1.2rem] sm:col-span-2 sm:aspect-[3/2]"><Image src="/images/studio-interior.webp" alt="Interior and seating at a modern barber studio" fill sizes="(max-width: 640px) 100vw, 66vw" className="object-cover"/></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-1"><div className="relative aspect-square overflow-hidden rounded-[1.2rem]"><Image src="/images/service-cut.webp" alt="Barber cutting a client’s hair" fill sizes="(max-width: 640px) 50vw, 33vw" className="object-cover"/></div><div className="relative aspect-square overflow-hidden rounded-[1.2rem]"><Image src="/images/service-shave.webp" alt="Barber tools prepared for a shave" fill sizes="(max-width: 640px) 50vw, 33vw" className="object-cover"/></div></div></div></section>
    <section className="border-t border-line bg-white px-5 py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_.8fr]"><div><p className="eyebrow">Find us</p><h2 className="display-type mt-3 text-4xl sm:text-5xl">Your next visit is close.</h2><p className="mt-5 max-w-lg text-base leading-7 text-muted">{business.address || "Contact us for our location."}</p><Link href="/contact" className="button-secondary mt-7">Location and contact details</Link></div><div className="surface-card p-6 sm:p-8"><h3 className="text-lg font-semibold">Opening hours</h3><div className="mt-4 space-y-1">{site.hours.length ? site.hours.map(hour => <div className="flex justify-between gap-3 border-b border-line py-2.5 text-sm" key={`${hour.weekday}-${hour.opens_at}`}><span>{["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][hour.weekday]}</span><span className="font-semibold">{hour.opens_at.slice(0,5)} – {hour.closes_at.slice(0,5)}</span></div>) : <p className="text-sm text-muted">Please contact us for opening hours.</p>}</div></div></div></section>
    <section className="bg-ink px-5 py-16 text-white sm:py-20"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-on-dark-accent">Ready when you are</p><h2 className="display-type mt-3 text-4xl sm:text-5xl">Make room for your next visit.</h2></div><Link href="/book" className="inline-flex min-h-13 items-center rounded-xl bg-accent-soft px-7 py-3 font-bold text-accent-dark hover:bg-white">Book an appointment <span aria-hidden="true" className="ml-3">↗</span></Link></div></section>
  </main>;
}
