import Link from "next/link";
import Image from "next/image";
import type { PublicWebsite } from "@/features/public-site/model";
import { imageUrl } from "@/features/public-site/data.server";
import { money } from "@/features/public-site/model";
import { demoServiceImage } from "@/features/public-site/demo-images";
export function SiteFooter({ site }: { site: PublicWebsite }) {
  return <footer className="mt-12 border-t border-line bg-white"><div className="mx-auto grid max-w-7xl gap-9 px-5 py-12 sm:grid-cols-3 sm:py-14"><div><p className="display-type text-2xl">{site.business?.name ?? "Our Studio"}</p><p className="mt-4 max-w-sm text-sm leading-7 text-muted">{site.business?.description}</p></div><div><h2 className="font-semibold">Visit us</h2><p className="mt-3 text-sm leading-7 text-muted">{site.business?.address ?? "Contact us for our location"}<br />{site.business?.contact_phone}<br />{site.business?.contact_email}</p></div><div><h2 className="font-semibold">Plan your visit</h2><p className="mt-3 text-sm leading-7 text-muted">Choose a service and time that suit you. We’ll keep you updated on your request.</p><div className="mt-4 flex flex-wrap gap-x-4 gap-y-2"><Link className="font-semibold text-accent-dark underline underline-offset-4" href="/book">Request an appointment</Link><Link className="font-semibold text-accent-dark underline underline-offset-4" href="/booking/manage">Manage booking</Link><Link className="font-semibold text-accent-dark underline underline-offset-4" href="/refund-policy">Refund policy</Link></div></div></div><div className="border-t border-line px-5 py-5 text-center text-xs text-muted">© {new Date().getFullYear()} {site.business?.name ?? "Our Studio"}</div></footer>;
}

export function ServiceCard({ service, currency, category, priority = false }: { priority?: boolean; service: PublicWebsite["services"][number]; currency: string; category?: string }) {
  const image = imageUrl(service.image_path) ?? demoServiceImage(service.name);
  const pay = service.payment_mode === "PAY_AT_BUSINESS" ? "Pay at your visit" : service.payment_mode === "DEPOSIT" ? `Deposit ${money(service.deposit_amount,currency)} after approval` : `Full payment ${money(service.price_amount,currency)} after approval`;
  return <article className="surface-card group flex h-full flex-col overflow-hidden"><div className="relative aspect-[4/3] overflow-hidden bg-accent-soft"><Image src={image} alt={service.image_path ? service.name : "Barber service demo photograph"} fill priority={priority} sizes="(max-width: 768px) 100vw, 33vw" unoptimized={Boolean(service.image_path)} className="object-cover transition-transform duration-300 group-hover:scale-[1.03]" /></div><div className="flex flex-1 flex-col p-5 sm:p-6"><p className="eyebrow">{category?`${category} · `:""}{service.duration_minutes} minutes</p><h2 className="display-type mt-3 text-2xl sm:text-3xl">{service.name}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-muted">{service.description || "A considered service, tailored to you."}</p><div className="mt-auto flex items-end justify-between gap-3 pt-6"><div><p className="text-xl font-bold text-ink">{money(service.price_amount,currency)}</p><p className="mt-1 text-xs leading-5 text-muted">{pay}</p></div><Link href={`/services/${service.slug}`} className="text-sm font-semibold text-accent-dark underline underline-offset-4">Details</Link></div><Link href={`/book?service=${service.slug}`} className="button-primary mt-5 w-full">Book this service</Link></div></article>;
}

export function StaffCard({ staff, services = [], priority = false }: { priority?: boolean; staff: PublicWebsite["staff"][number]; services?: string[] }) {
  const image = imageUrl(staff.photo_path) ?? "/images/staff-portrait.webp";
  return <article className="surface-card group h-full overflow-hidden"><div className="relative aspect-[4/3] overflow-hidden bg-accent-soft"><Image src={image} alt={staff.photo_path ? `${staff.display_name}, service professional` : "Representative demo portrait of a barber"} fill priority={priority} sizes="(max-width: 768px) 100vw, 33vw" unoptimized={Boolean(staff.photo_path)} className="object-cover transition-transform duration-300 group-hover:scale-[1.03]" />{!staff.photo_path&&<span className="absolute bottom-3 left-3 rounded-md bg-white/95 px-2 py-1 text-[10px] font-semibold text-ink">Demo portrait</span>}</div><div className="p-5 sm:p-6"><h2 className="display-type text-2xl sm:text-3xl">{staff.display_name}</h2><p className="mt-3 line-clamp-3 min-h-18 text-sm leading-6 text-muted">{staff.bio || "Meet your service professional."}</p>{services.length>0&&<p className="mt-3 text-xs leading-5 text-muted">Services: {services.join(", ")}</p>}<Link href={`/team/${staff.slug}`} className="mt-5 inline-block text-sm font-semibold text-accent-dark underline underline-offset-4">Meet {staff.display_name}</Link></div></article>;
}
