"use client";
import Link from "next/link";
import Image from "next/image";
import { useActionState, useEffect, useRef, useState } from "react";
import type { PublicWebsite } from "./model";
import { money } from "./model";
import { submitBookingAction, signOutForGuestBookingAction } from "./booking-actions";
import type { AvailabilityResult, AvailabilitySlot } from "@/features/availability/schemas";
import { demoServiceImage } from "./demo-images";

type Props={site:PublicWebsite;serviceSlug?:string;staffSlug?:string;customer:null|{name:string;email:string;phone:string|null};today:string;maxDate:string;requestKeySeed:string};
const steps=["Service","Professional","Date","Time","Your details","Review"];
export function BookingWizard({site,serviceSlug,staffSlug,customer,today,maxDate,requestKeySeed}:Props){
 const initialServiceId=site.services.find(x=>x.slug===serviceSlug)?.id??"";
 const initialStaffId=site.staff.find(x=>x.slug===staffSlug&&site.assignments.some(a=>a.staff_id===x.id&&a.service_id===initialServiceId))?.id??"";
 const [step,setStep]=useState(0),[serviceId,setServiceId]=useState(initialServiceId),[staffId,setStaffId]=useState(initialStaffId),[date,setDate]=useState(""),[slot,setSlot]=useState<AvailabilitySlot|null>(null),[availability,setAvailability]=useState<AvailabilityResult|null>(null),[loading,setLoading]=useState(false),[availabilityError,setAvailabilityError]=useState(""),[name,setName]=useState(customer?.name??""),[email,setEmail]=useState(customer?.email??""),[phone,setPhone]=useState(customer?.phone??""),[contactAttempted,setContactAttempted]=useState(false),[requestKey,setRequestKey]=useState(requestKeySeed),[state,action,pending]=useActionState(submitBookingAction,{});
 const stepHeadingRef=useRef<HTMLHeadingElement>(null);
 const service=site.services.find(x=>x.id===serviceId), eligible=site.staff.filter(x=>site.assignments.some(a=>a.staff_id===x.id&&a.service_id===serviceId));
 const preferredStaff=site.staff.find(x=>x.slug===staffSlug&&eligible.some(y=>y.id===x.id));
 const fingerprint=`${serviceId}:${staffId}:${date}:${slot?.starts_at??""}`;
 useEffect(()=>{if(step>0)stepHeadingRef.current?.focus()},[step]);
 useEffect(()=>{if(!serviceId||!date)return;let alive=true;const timer=window.setTimeout(()=>{if(alive)setLoading(true)},0);const params=new URLSearchParams({service:serviceId,date,...(staffId?{staff:staffId}:{})});fetch(`/api/availability?${params}`,{cache:"no-store"}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error||"Availability could not be loaded.");if(alive)setAvailability(value as AvailabilityResult)}).catch(error=>{if(alive){setAvailability(null);setAvailabilityError(error instanceof Error?error.message:"Availability could not be loaded.")}}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false;window.clearTimeout(timer)}},[serviceId,date,staffId]);
 useEffect(()=>{const timer=window.setTimeout(()=>{const key=`public-booking:${fingerprint}`;let value=sessionStorage.getItem(key);if(!value){value=requestKeySeed;sessionStorage.setItem(key,value)}setRequestKey(value)},0);return()=>window.clearTimeout(timer)},[fingerprint,requestKeySeed]);
 const canContinue=step===0?Boolean(service):step===1?Boolean(eligible.length):step===2?Boolean(date):step===3?Boolean(slot):true;
 function changeService(value:string){setServiceId(value);setStaffId("");setDate("");setSlot(null);setAvailability(null);setAvailabilityError("")}
 function changeStaff(value:string){setStaffId(value);setDate("");setSlot(null);setAvailability(null);setAvailabilityError("")}
 function next(){if(step===4){setContactAttempted(true);if(!name.trim()||!/^\S+@\S+\.\S+$/.test(email.trim()))return}if(step===0&&service){setStaffId(preferredStaff?.id??"")}setStep(s=>Math.min(s+1,5))}
 const payment=service?.payment_mode==="PAY_AT_BUSINESS"?"Pay at the business":service?.payment_mode==="DEPOSIT"?`Deposit of ${money(service.deposit_amount,site.business?.currency??"USD")} after acceptance`:`Full payment of ${money(service?.price_amount??0,site.business?.currency??"USD")} after acceptance`;
 return <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 sm:py-14"><div className="mb-8"><p className="eyebrow">Request an appointment</p><h1 className="display-type mt-3 text-4xl sm:text-5xl">Let’s plan your visit.</h1><p className="mt-3 max-w-2xl text-muted">Choose what works for you. {site.business?.booking_approval_mode==="AUTO_CONFIRM"?"If the time is still available, your booking will be reserved immediately.":"Our team will review the request before reserving the time."}</p></div>
 {!customer&&site.business&&!site.business.guest_booking_enabled&&<div className="mb-6 rounded-2xl border border-warning/30 bg-warning-soft p-5"><h2 className="font-semibold">Sign in to request an appointment</h2><p className="mt-1 text-sm text-muted">Guest booking is disabled for this business.</p><div className="mt-3 flex gap-4"><Link className="underline" href="/login?next=%2Fbook">Sign in</Link>{site.business.customer_registration_enabled&&<Link className="underline" href="/register">Create an account</Link>}</div></div>}
 <div className="mb-7 sm:hidden"><div className="mb-3 flex items-center justify-between gap-4 text-sm"><p className="font-semibold">{steps[step]}</p><p className="text-muted">Step {step+1} of {steps.length}</p></div><div role="progressbar" aria-label="Booking progress" aria-valuemin={1} aria-valuemax={steps.length} aria-valuenow={step+1} className="h-1.5 overflow-hidden rounded-full bg-line"><div className="h-full rounded-full bg-accent transition-[width] duration-200" style={{width:`${((step+1)/steps.length)*100}%`}}/></div></div>
 <ol aria-label="Booking progress" className="mb-7 hidden gap-2 sm:grid sm:grid-cols-6">{steps.map((label,index)=><li key={label} aria-current={index===step?"step":undefined} className={`min-w-24 rounded-xl px-3 py-2.5 text-center text-xs sm:min-w-0 ${index===step?"bg-accent text-white":"bg-line text-muted"}`}><span className="block font-semibold">{index+1}</span>{label}</li>)}</ol>
 {step>0&&service&&<aside aria-label="Current booking selection" className="mb-5 flex flex-wrap items-center gap-x-5 gap-y-2 rounded-2xl border border-line bg-surface px-5 py-4 text-sm"><span className="font-semibold text-ink">{service.name}</span><span className="text-muted">{money(service.price_amount,site.business?.currency??"USD")} · {service.duration_minutes} min</span>{date&&<span className="text-muted">{date}{slot?` · ${slot.local_time}`:""}</span>}</aside>}
 <form action={action} className="surface-card p-5 sm:p-8">
 <input type="hidden" name="serviceId" value={serviceId}/><input type="hidden" name="staffId" value={staffId}/><input type="hidden" name="startsAt" value={slot?.starts_at??""}/><input type="hidden" name="requestKey" value={requestKey}/><input type="hidden" name="fullName" value={name}/><input type="hidden" name="email" value={email}/><input type="hidden" name="phone" value={phone}/>
 {step===0&&<section aria-labelledby="step-service"><h2 ref={stepHeadingRef} tabIndex={-1} id="step-service" className="display-type text-3xl">Choose a service</h2><p className="mt-2 text-sm text-muted">Select one service to see who and when you can book.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{site.services.map(item=><label key={item.id} className={`relative flex cursor-pointer items-center gap-4 rounded-2xl border p-3 transition ${serviceId===item.id?"border-accent ring-1 ring-accent bg-accent-soft/40":"border-line bg-surface hover:border-accent/50"}`}><span className="relative block size-20 shrink-0 overflow-hidden rounded-xl"><Image src={demoServiceImage(item.name)} alt="" fill loading="eager" sizes="80px" className="object-cover"/></span><span className="min-w-0 flex-1"><span className="block font-semibold">{item.name}</span><span className="mt-1 block text-sm text-muted">{item.duration_minutes} min · {money(item.price_amount,site.business?.currency??"USD")}</span></span><input type="radio" name="serviceChoice" value={item.id} checked={serviceId===item.id} onChange={()=>changeService(item.id)} className="size-5 shrink-0 accent-accent"/></label>)}</div>{!site.services.length&&<p className="mt-4 text-muted">No services are currently available for online booking.</p>}</section>}
 {step===1&&<section aria-labelledby="step-staff"><h2 ref={stepHeadingRef} tabIndex={-1} id="step-staff" className="display-type text-3xl">Choose a professional</h2><p className="mt-2 text-sm text-muted">Only professionals offering {service?.name} are shown.</p><div className="mt-5 grid gap-3"><label className={`flex cursor-pointer items-center gap-4 rounded-2xl border p-4 ${staffId===""?"border-accent ring-1 ring-accent bg-accent-soft/40":"border-line"}`}><input type="radio" name="staffChoice" checked={!staffId} onChange={()=>changeStaff("")} className="size-4 accent-accent"/><span><span className="block font-medium">Any available professional</span><span className="text-sm text-muted">We’ll recommend an eligible team member for the time you choose.</span></span></label>{eligible.map(person=><label key={person.id} className={`flex cursor-pointer items-center gap-4 rounded-2xl border p-4 ${staffId===person.id?"border-accent ring-1 ring-accent bg-accent-soft/40":"border-line"}`}><input type="radio" name="staffChoice" checked={staffId===person.id} onChange={()=>changeStaff(person.id)} className="size-4 accent-accent"/><span className="font-medium">{person.display_name}</span></label>)}</div></section>}
 {step===2&&<section aria-labelledby="step-date"><h2 ref={stepHeadingRef} tabIndex={-1} id="step-date" className="display-type text-3xl">Choose a date</h2><p className="mt-2 text-sm text-muted">Dates and times use {site.business?.timezone} business time.</p><label className="mt-6 block max-w-sm text-sm font-medium" htmlFor="booking-date">Appointment date</label><input id="booking-date" type="date" min={today} max={maxDate} value={date} onChange={e=>{setDate(e.target.value);setSlot(null);setAvailability(null);setAvailabilityError("")}} className="mt-2 min-h-12 w-full max-w-sm rounded-control border border-line bg-surface px-4" aria-describedby="date-help"/><p id="date-help" className="mt-2 text-sm text-muted">Booking notice and advance-window rules are checked again when you submit.</p></section>}
 {step===3&&<section aria-labelledby="step-time"><h2 ref={stepHeadingRef} tabIndex={-1} id="step-time" className="display-type text-3xl">Choose a time</h2><p className="mt-2 text-sm text-muted">Available start times for {date}.</p>{loading&&<p role="status" className="mt-6 rounded-xl bg-canvas p-4">Checking availability…</p>}{availabilityError&&<p role="alert" className="mt-6 rounded-xl bg-danger-soft p-4 text-danger">{availabilityError}</p>}{!loading&&!availabilityError&&availability?.slots.length===0&&<p className="mt-6 rounded-xl bg-canvas p-4">There are no available times on this date. Choose another date.</p>}<div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{availability?.slots.map(option=><button type="button" key={`${option.starts_at}-${option.assigned_staff_id}`} aria-pressed={slot?.starts_at===option.starts_at} onClick={()=>setSlot(option)} className={`min-h-12 rounded-xl border px-3 py-3 font-semibold ${slot?.starts_at===option.starts_at?"border-accent bg-accent text-white":"border-line"}`}>{option.local_time}</button>)}</div>{slot&&<p className="mt-4 text-sm text-muted">{staffId?`With ${eligible.find(x=>x.id===staffId)?.display_name}`:`Recommended: ${slot.staff.find(x=>x.id===slot.assigned_staff_id)?.display_name||"available team member"}`}. {site.business?.booking_approval_mode==="AUTO_CONFIRM"?"The time will be reserved during submission if it is still available.":"This is a request only until accepted."}</p>}</section>}
 {step===4&&<section aria-labelledby="step-contact"><h2 ref={stepHeadingRef} tabIndex={-1} id="step-contact" className="display-type text-3xl">Your details</h2>{customer?<div className="mt-4 rounded-2xl border border-accent/30 bg-accent-soft p-4"><p className="eyebrow">Booking as</p><p className="mt-2 font-semibold">{customer.name}</p><p className="text-sm text-muted">{customer.email}</p><p className="mt-2 text-sm text-muted">Your appointment will be saved to your account. Your verified email stays tied to this booking.</p><button type="submit" formNoValidate formAction={signOutForGuestBookingAction} className="mt-3 text-sm font-semibold text-accent-dark underline">Not you? Sign out and book as guest</button></div>:<p className="mt-2 text-sm text-muted">No account needed. Enter your contact details to make this booking.</p>}<div className="mt-5 grid gap-4"><div><label className="block text-sm font-medium" htmlFor="booking-name">Full name</label><input id="booking-name" required minLength={2} maxLength={200} autoComplete="name" aria-invalid={contactAttempted&&!name.trim()} aria-describedby={contactAttempted&&!name.trim()?"booking-name-error":undefined} value={name} onChange={e=>setName(e.target.value)} className="mt-2 min-h-12 w-full rounded-control border border-line bg-surface px-4"/>{contactAttempted&&!name.trim()&&<p id="booking-name-error" className="mt-1 text-sm text-danger">Enter your full name.</p>}</div><div><label className="block text-sm font-medium" htmlFor="booking-email">Email address</label><input id="booking-email" required type="email" maxLength={254} autoComplete="email" readOnly={Boolean(customer)} aria-invalid={contactAttempted&&!/^\S+@\S+\.\S+$/.test(email.trim())} aria-describedby={contactAttempted&&!/^\S+@\S+\.\S+$/.test(email.trim())?"booking-email-error":"booking-email-help"} value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 min-h-12 w-full rounded-control border border-line bg-surface px-4 read-only:bg-canvas"/><span id="booking-email-help" className="mt-1 block text-xs font-normal text-muted">{customer?"Your verified account email is locked for this booking. Change it in account settings if needed.":"We need an email address to identify your request."}</span>{contactAttempted&&!/^\S+@\S+\.\S+$/.test(email.trim())&&<p id="booking-email-error" className="mt-1 text-sm text-danger">Enter a valid email address.</p>}</div><div><label className="block text-sm font-medium" htmlFor="booking-phone">Mobile number <span className="font-normal text-muted">(optional)</span></label><input id="booking-phone" type="tel" maxLength={25} autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)} className="mt-2 min-h-12 w-full rounded-control border border-line bg-surface px-4"/></div></div></section>}
 {step===5&&<section aria-labelledby="step-review"><h2 ref={stepHeadingRef} tabIndex={-1} id="step-review" className="display-type text-3xl">Review your request</h2><dl className="mt-5 divide-y divide-line rounded-2xl border border-line px-4"><ReviewLine term="Service" value={service?.name??""}/><ReviewLine term="Professional" value={staffId?eligible.find(x=>x.id===staffId)?.display_name??"Selected professional":`Any available · ${slot?.staff.find(x=>x.id===slot.assigned_staff_id)?.display_name??"assigned on request"}`}/><ReviewLine term="Date and time" value={slot&&availability?new Intl.DateTimeFormat("en",{timeZone:availability.timezone,dateStyle:"full",timeStyle:"short"}).format(new Date(slot.starts_at)):date}/><ReviewLine term="Duration" value={`${service?.duration_minutes??"—"} minutes`}/><ReviewLine term="Price" value={money(service?.price_amount??0,site.business?.currency??"USD")}/><ReviewLine term="Payment" value={payment??"—"}/><ReviewLine term="Customer" value={`${name} · ${email}${phone?` · ${phone}`:""}`}/></dl><div className="mt-5 rounded-2xl bg-warning-soft p-4 text-sm leading-6 text-ink">{site.business?.booking_approval_mode==="AUTO_CONFIRM"?<><strong>Immediate booking:</strong> we will recheck availability when you submit. If the time is free, it will be reserved immediately. A deposit or full-payment booking will require payment within the displayed window.</>:<><strong>Request only:</strong> submitting does not reserve this time. The business will review your request, and the appointment is reserved only after it is accepted. Any required deposit or payment will be requested after acceptance.</>}</div><details className="mt-5 rounded-xl border border-line p-4"><summary className="cursor-pointer font-medium">Cancellation and booking policy</summary><p className="mt-3 whitespace-pre-line text-sm leading-6 text-muted">{site.policy?.terms||"Please contact the business if you need to change a request. Deposit or full payment is never collected before acceptance."}</p><p className="mt-2 text-sm text-muted">Cancellation notice: {site.policy?.cancellation_notice_minutes??0} minutes where applicable.</p></details>{state.error&&<p role="alert" className="mt-5 rounded-xl bg-danger-soft p-4 text-sm text-danger">{state.error}</p>}</section>}
 <div className="mt-8 flex flex-col-reverse justify-between gap-3 border-t border-line pt-5 sm:flex-row">{step>0?<button type="button" onClick={()=>setStep(s=>s-1)} className="min-h-12 rounded-xl border border-line bg-surface px-6 font-semibold">Back</button>:<span/>}{step<5?<button type="button" disabled={!canContinue} onClick={next} className="min-h-12 rounded-xl bg-accent px-7 font-semibold text-white hover:bg-accent-dark disabled:cursor-not-allowed disabled:bg-line disabled:text-muted">Continue</button>:<button type="submit" disabled={pending||!service||!slot||(!customer&&site.business?.guest_booking_enabled===false)} className="min-h-12 rounded-xl bg-accent px-7 font-semibold text-white hover:bg-accent-dark disabled:cursor-wait disabled:bg-line disabled:text-muted">{pending?"Submitting request…":"Submit appointment request"}</button>}</div>
 </form><p className="mx-auto mt-5 max-w-2xl text-center text-xs leading-5 text-muted">Only currently available times are shown. Availability is checked again when you submit. {site.business?.booking_approval_mode==="AUTO_CONFIRM"?"Automatic bookings reserve the slot only after the final availability check succeeds.":"Appointment requests remain pending and do not reserve a slot until accepted."}</p></main>;
}
function ReviewLine({term,value}:{term:string;value:string}){return <div className="grid gap-1 py-4 sm:grid-cols-[160px_1fr] sm:gap-4"><dt className="text-sm text-muted">{term}</dt><dd className="text-sm font-medium">{value}</dd></div>}
